<a href="https://colab.research.google.com/github/sitbayevalibek/Pandas_dataset_Central_Asian/blob/main/Pandas_dataset_Central_Asian.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Population growth of Central Asian countries in 2016-2021**
Dataset [TheWorldBank](https://data.worldbank.org/indicator/SP.POP.TOTL?end=2021&locations=UZ&start=2016)

In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame

In [2]:
data = {
    'Afghanistan':{2016:34.6, 2017:35.6, 2018:36.7, 2019:37.8, 2020:39, 2021:40.1},
    'Kazakhstan':{2016:17.8, 2017:18, 2018:18.3, 2019:18.5, 2020:18.8, 2021:19},
    'Kyrgyzstan':{2016:6.1, 2017:6.2, 2018:6.3, 2019:6.5, 2020:6.6, 2021:6.7},
    'Tajikistan':{2016:8.7, 2017:9, 2018:9.1, 2019:9.3, 2020:9.5, 2021:9.8},
    'Turkmenistan':{2016:5.9, 2017:6, 2018:6.1, 2019:6.2, 2020:6.3, 2021:6.4},
    'Uzbekistan':{2016:31.8, 2017:32.4, 2018:33, 2019:33.6, 2020:34.2, 2021:34.9}
}
df = DataFrame(data)
df

,Afghanistan,Kazakhstan,Kyrgyzstan,Tajikistan,Turkmenistan,Uzbekistan
2016,34.6,17.8,6.1,8.7,5.9,31.8
2017,35.6,18.0,6.2,9.0,6.0,32.4
2018,36.7,18.3,6.3,9.1,6.1,33.0
2019,37.8,18.5,6.5,9.3,6.2,33.6
2020,39.0,18.8,6.6,9.5,6.3,34.2
2021,40.1,19.0,6.7,9.8,6.4,34.9

In [3]:
df.index.name = 'Year'
df

,Afghanistan,Kazakhstan,Kyrgyzstan,Tajikistan,Turkmenistan,Uzbekistan
Year,,,,,,
2016,34.6,17.8,6.1,8.7,5.9,31.8
2017,35.6,18.0,6.2,9.0,6.0,32.4
2018,36.7,18.3,6.3,9.1,6.1,33.0
2019,37.8,18.5,6.5,9.3,6.2,33.6
2020,39.0,18.8,6.6,9.5,6.3,34.2
2021,40.1,19.0,6.7,9.8,6.4,34.9